# Generated by Django 6.0 on 2025-12-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('steps', models.IntegerField(default=0)),
                ('sleep_hours', models.FloatField(default=0)),
                ('water_glasses', models.IntegerField(default=0)),
                ('active_minutes', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('date',)},
            },
        ),
    ]
